### ISSUE TITLE
Github Action not working properly

### ISSUE THREAD

**Issue by Geek-ubaid** [GDGVIT/dsc-links-portal#2]
The Github workflow is not working properly, all the actions were running for around 4 hours continuously. Check the action file or your code for any code or error.

**Comment by ATechnoHazard** [comment]
Github actions logs show that the tests failed to connect to redis locally.

**Comment by Geek-ubaid** [comment]
> Github actions logs show that the tests failed to connect to redis locally.

Try to figure out the issue and sort it if its an issue in the template.

**Comment by ATechnoHazard** [comment]
It's not an issue with the template. The action is trying to run tests, but the API requires a connection to redis. I recommend @mdhishaamakhtar add a redis github action and connect to it.

**Comment by mdhishaamakhtar** [comment]
Redis Server has been added and issue is resolved now
